### PR TITLE
Testing To Do list

### PR DESCRIPTION
**Pull request by kiboma2021**
- Use jest framework for testing.
- Create a test file ([..].test.js) for a file containing the add item and delete item functions that you want to test.
- Take a look at each of these functions. Are they pure functions? If the answer is "yes" then writing tests for them should be straightforward. Some of those functions however will update localStorage and manipulate the DOM. For those, you will need to use mocks:
- Mock a storage object to "imitate" localStorage operations (only if you are using jest < 24.x, in newer versions localStorage is mocked automatically).
- Mock HTML to test if add/delete functions add or remove exactly one <li> element to/from the list in the DOM.
- Make sure you group your tests using the describe() method.

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
Hi @kiboma2021 , @rebel216 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rebel216** [comment]
> ## Required Changes ♻️
> * [ ]  Your tests are not running successfully. Seems you didn't install jest: check the screenshot below:
> 
> Screenshot from 2022-06-09 23-24-04
> 
> After installing jest, I ran `npm run test` and was hit with failing tests: Screenshot.
> 
> Screenshot from 2022-06-09 23-36-12
> 
> Please fix the issues and submit your project once more.
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hey , Thanks for the review  , But tests are being done successfully on my side 
Screenshot 2022-06-10 at 4 27 06 AM
.

**Review by OmarRamoun — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @team 👋

Your project is complete! ✔️ 🏁

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [@omarramoun](https://github.com/omarramoun)
- This is My **Twitter**: [@omarramoun](https://twitter.com/omarramoun)
- This is My **Slack**: [Ramoun](https://slack.com)
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rebel216** [comment]
> > > ## Required Changes recycle
> > > 
> > > * [ ]    Your tests are not running successfully. Seems you didn't install jest: check the screenshot below:
> > > 
> > > Screenshot from 2022-06-09 23-24-04
> > > After installing jest, I ran `npm run test` and was hit with failing tests: Screenshot.
> > > Screenshot from 2022-06-09 23-36-12
> > > Please fix the issues and submit your project once more.
> > > _Check the comments under the review._
> > > ## Optional suggestions
> > > _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> > > Cheers and Happy coding!clapclapclap
> > > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> > > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> > 
> > 
> > Hey , Thanks for the review , But tests are being done successfully on my side Screenshot 2022-06-10 at 4 27 06 AM .
> 
> Hi @rebel216. Nice to hear that.
> 
> You can always verify that particular commit before criticizing 😄

I wasn't criticising bro :) . But made another commit to ensure that the problem is not on my end 👍

**Pull request merged**
