### PR TITLE
Interactive list

### PR DESCRIPTION
**Pull request by rebel216**
Created Interactive list , added Edit , delete and clear completed features.

### CODE REVIEW

**Review by ShoiraTa — CHANGES_REQUESTED** [review]
Hi @rebel216 ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- You passed all the Linters! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!



 ## Required Changes  :recycle: 

- [x] When adding new items I am getting an error: 
Screenshot 2022-06-03 at 21 00 12
The reason is in List.js file, line 15,     `toDoItems.push(...storedToDoList)` ;
Kindly clean localStorage using localStorage.clear(), and try to debug the error

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rebel216** [comment]
> Hi @rebel216 ,
> 
> 👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> 
> **First let me to point out:**
> 
> * You passed all the Linters! ✔️
> 
> Keep on coding, good job so far! 👏
> 
> There are some issues that you still need to work on to go to the next project but you are almost there!
> 
>  [ ](https://camo.githubusercontent.com/7a3175b24229512cc970aece8b2e2de8a06ce098a4f0ba2c4079f9a4f9152c29/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966) 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966 [ ](https://camo.githubusercontent.com/7a3175b24229512cc970aece8b2e2de8a06ce098a4f0ba2c4079f9a4f9152c29/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966)
> 
> ## Required Changes ♻️
> * [x]  When adding new items I am getting an error:
> 
> Screenshot 2022-06-03 at 21 00 12
> 
> The reason is in List.js file, line 15, `toDoItems.push(...storedToDoList)` ; Kindly clean localStorage using localStorage.clear(), and try to debug the error
> Cheers and Happy coding! 👏 👏 👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

hey ,
I am not getting any error .. please explain it.

**Comment by ShoiraTa** [comment]
Hey @rebel216 , I assume that you are not getting an error because the local storage has some cached data, try to clear it and clear browser cache and to start app again, if you still don't get any error please let me know I will check again

**Comment by rebel216** [comment]
> Hey @rebel216 , I assume that you are not getting an error because the local storage has some cached data, try to clear it and clear browser cache and to start app again, if you still don't get any error please let me know I will check again

hello , Done it , but still not getting the error . 👍

**Review by OmarRamoun — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @rebel216 👋

Your project is complete! ✔️ 🏁

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [@omarramoun](https://github.com/omarramoun)
- This is My **Twitter**: [@omarramoun](https://twitter.com/omarramoun)
- This is My **Slack**: [Ramoun](https://slack.com)
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
